language: python
virtualenv:
  system_site_packages: true
git:
  depth: 2
python:
  # 2.7
  # - 3.4
  # - 3.5
  - 3.6
branches:
  only:
  - master
script:
  - pytest
install:
  - pip install -r requirements.txt
